export const data = {
  cards: [
   {
     id: 1,
     cardname: "John Doe",
     ATK: 30,
     DEF: 20,
     Star: 8,
     Type: "Warrior",
     Effect: "Increases attack power by 10%",
     Image: "https://example.com/image1.jpg",
     Description: "A brave warrior with unmatched strength.",
   },
   {
     id: 2,
     cardname: "Jane Smith",
     ATK: 25,
     DEF: 30,
     Star: 7,
     Type: "Mage",
     Effect: "Casts powerful spells.",
     Image: "https://example.com/image2.jpg",
     Description: "A wise mage with a deep understanding of magic.",
   },
   {
     id: 3,
     cardname: "Sam Brown",
     ATK: 20,
     DEF: 25,
     Star: 6,
     Type: "Rogue",
     Effect: "Stealthy and agile.",
     Image: "https://example.com/image3.jpg",
     Description: "A cunning rogue who strikes from the shadows.",
   },
   {
     id: 4,
     cardname: "Emily Davis",
     ATK: 35,
     DEF: 15,
     Star: 9,
     Type: "Paladin",
     Effect: "Protects allies with a shield.",
     Image: "https://example.com/image4.jpg",
     Description: "A noble paladin who defends the weak.",
   },
   {
     id: 5,
     cardname: "Michael Johnson",
     ATK: 28,
     DEF: 22,
     Star: 7,
     Type: "Archer",
     Effect: "Shoots arrows with precision.",
     Image: "https://example.com/image5.jpg",
     Description: "An expert archer with unmatched aim.",
   },
   {
     id: 6,
     cardname: "Sarah Wilson",
     ATK: 22,
     DEF: 28,
     Star: 6,
     Type: "Healer",
     Effect: "Restores health to allies.",
     Image: "https://example.com/image6.jpg",
     Description: "A compassionate healer who mends wounds.",
   },
  ]
 }